In [14]:
from itertools import groupby 

fname = 'popular-names.txt'
col1 = []

with open(fname) as file:
    for line in file:
        element = line.split()
        col1.append(element[0])
        col1.sort()
        
result = [[len(list(g)), k] for k, g in groupby(col1)]
result.sort(key=lambda r:r[0], reverse=True)

for r in result:
    print('{0} {1}'.format(r[0], r[1]))

118 James
111 William
108 John
108 Robert
92 Mary
75 Charles
74 Michael
73 Elizabeth
70 Joseph
60 Margaret
58 George
58 Thomas
57 David
51 Richard
45 Helen
43 Christopher
43 Frank
41 Anna
40 Edward
39 Ruth
38 Patricia
37 Matthew
36 Dorothy
35 Emma
32 Barbara
31 Daniel
31 Joshua
26 Emily
26 Jennifer
26 Linda
26 Sarah
25 Jacob
25 Jessica
24 Betty
24 Mildred
24 Susan
23 Ashley
23 Henry
22 Nancy
21 Andrew
20 Amanda
20 Donald
20 Florence
20 Marie
19 Samantha
18 Karen
18 Lisa
18 Madison
18 Melissa
18 Olivia
17 Abigail
17 Stephanie
16 Ethel
16 Mark
16 Sandra
15 Angela
15 Carol
15 Ethan
15 Frances
15 Heather
15 Isabella
15 Michelle
14 Amy
14 Ava
14 Kimberly
14 Shirley
13 Brian
13 Deborah
13 Hannah
13 Jason
13 Nicole
13 Sophia
13 Virginia
12 Bertha
12 Donna
12 Minnie
11 Cynthia
10 Alice
10 Brittany
10 Doris
10 Mia
10 Nicholas
10 Noah
10 Ronald
9 Debra
9 Joan
9 Tyler
8 Alexander
8 Alexis
8 Clara
8 Ida
8 Judith
8 Mason
8 Taylor
7 Brandon
7 Harry
7 Liam
7 Sharon
7 Steven
7 Tammy
6 Anthony
5 Annie
5 Charlotte
5 Gary
5 Jayden
5 Jeffrey
4 Austin
4 Benjamin
4 Chloe
4 Justin
4 Kathleen
4 Lillian
3 Aiden
3 Elijah
3 Evelyn
3 Harper
3 Megan
2 Amelia
2 Bessie
2 Larry
2 Lauren
2 Logan
2 Oliver
2 Rebecca
1 Carolyn
1 Crystal
1 Julie
1 Kelly
1 Laura
1 Lori
1 Lucas
1 Pamela
1 Rachel
1 Scott
1 Tracy
1 Walter